// types.js
const TYPES = {
  string: {
    label: "string",
    cat: "values",
    col: "var(--col-val)",
    fields: [{ id: "v", label: "value", kind: "text", def: "hello" }],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `"${(n.f.v || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`,
  },
  number: {
    label: "number",
    cat: "values",
    col: "var(--col-val)",
    fields: [{ id: "v", label: "value", kind: "number", def: "0" }],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${n.f.v || "0"}`,
  },
  boolean: {
    label: "boolean",
    cat: "values",
    col: "var(--col-val)",
    fields: [
      {
        id: "v",
        label: "value",
        kind: "select",
        opts: ["true", "false"],
        def: "true",
      },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${n.f.v || "true"}`,
  },
  null_val: {
    label: "null",
    cat: "values",
    col: "var(--col-val)",
    fields: [],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: () => "null",
  },
  undefined_val: {
    label: "undefined",
    cat: "values",
    col: "var(--col-val)",
    fields: [],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: () => "undefined",
  },
  variable: {
    label: "variable",
    cat: "variables",
    col: "var(--col-var)",
    fields: [
      {
        id: "kind",
        label: "kind",
        kind: "select",
        opts: ["let", "const", "var"],
        def: "let",
      },
      { id: "name", label: "name", kind: "text", def: "x" },
    ],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "ref", label: "ref" }],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `${n.f.kind || "let"} ${n.f.name || "x"} = ${ge(n.id, "val")};`,
    ref: (n) => n.f.name || "x",
  },
  assign: {
    label: "assign",
    cat: "variables",
    col: "var(--col-var)",
    fields: [{ id: "name", label: "variable name", kind: "text", def: "x" }],
    ins: [{ id: "val", label: "value" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${n.f.name || "x"} = ${ge(n.id, "val")};`,
  },
  add: {
    label: "add",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} + ${ge(n.id, "b")})`,
  },
  subtract: {
    label: "subtract",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} - ${ge(n.id, "b")})`,
  },
  multiply: {
    label: "multiply",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} * ${ge(n.id, "b")})`,
  },
  divide: {
    label: "divide",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} / ${ge(n.id, "b")})`,
  },
  modulo: {
    label: "modulo",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} % ${ge(n.id, "b")})`,
  },
  power: {
    label: "power",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "base" },
      { id: "b", label: "exp" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.pow(${ge(n.id, "a")}, ${ge(n.id, "b")})`,
  },
  abs: {
    label: "abs",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.abs(${ge(n.id, "a")})`,
  },
  floor: {
    label: "floor",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.floor(${ge(n.id, "a")})`,
  },
  ceil: {
    label: "ceil",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.ceil(${ge(n.id, "a")})`,
  },
  round: {
    label: "round",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.round(${ge(n.id, "a")})`,
  },
  random: {
    label: "random",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: () => `Math.random()`,
  },
  min: {
    label: "min",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.min(${ge(n.id, "a")}, ${ge(n.id, "b")})`,
  },
  max: {
    label: "max",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.max(${ge(n.id, "a")}, ${ge(n.id, "b")})`,
  },
  compare: {
    label: "compare",
    cat: "logic",
    col: "var(--col-logic)",
    fields: [
      {
        id: "op",
        label: "operator",
        kind: "select",
        opts: ["===", "!==", "<", ">", "<=", ">="],
        def: "===",
      },
    ],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} ${n.f.op || "==="} ${ge(n.id, "b")})`,
  },
  and: {
    label: "and",
    cat: "logic",
    col: "var(--col-logic)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} && ${ge(n.id, "b")})`,
  },
  or: {
    label: "or",
    cat: "logic",
    col: "var(--col-logic)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} || ${ge(n.id, "b")})`,
  },
  not: {
    label: "not",
    cat: "logic",
    col: "var(--col-logic)",
    fields: [],
    ins: [{ id: "a", label: "a" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(!${ge(n.id, "a")})`,
  },
  nullish: {
    label: "nullish (??)",
    cat: "logic",
    col: "var(--col-logic)",
    fields: [],
    ins: [
      { id: "a", label: "value" },
      { id: "b", label: "fallback" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} ?? ${ge(n.id, "b")})`,
  },
  ternary: {
    label: "if / else",
    cat: "control",
    col: "var(--col-flow)",
    fields: [],
    ins: [
      { id: "cond", label: "condition" },
      { id: "then", label: "then" },
      { id: "else", label: "else" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `(${ge(n.id, "cond")} ? ${ge(n.id, "then")} : ${ge(n.id, "else")})`,
  },
  if_stmt: {
    label: "if statement",
    cat: "control",
    col: "var(--col-flow)",
    fields: [
      { id: "body", label: "body (raw js)", kind: "text", def: "// body here" },
    ],
    ins: [{ id: "cond", label: "condition" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `if (${ge(n.id, "cond")}) {\n  ${n.f.body || ""}\n}`,
  },
  for_loop: {
    label: "for loop",
    cat: "control",
    col: "var(--col-flow)",
    fields: [
      { id: "init", label: "init", kind: "text", def: "let i = 0" },
      { id: "cond", label: "condition", kind: "text", def: "i < 10" },
      { id: "update", label: "update", kind: "text", def: "i++" },
      { id: "body", label: "body", kind: "text", def: "console.log(i)" },
    ],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) =>
      `for (${n.f.init || ""}; ${n.f.cond || ""}; ${n.f.update || ""}) {\n  ${n.f.body || ""}\n}`,
  },
  while_loop: {
    label: "while loop",
    cat: "control",
    col: "var(--col-flow)",
    fields: [{ id: "body", label: "body", kind: "text", def: "" }],
    ins: [{ id: "cond", label: "condition" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `while (${ge(n.id, "cond")}) {\n  ${n.f.body || ""}\n}`,
  },
  switch_stmt: {
    label: "switch",
    cat: "control",
    col: "var(--col-flow)",
    fields: [
      {
        id: "cases",
        label: "cases (raw js)",
        kind: "text",
        def: "case 'a': break;",
      },
    ],
    ins: [{ id: "val", label: "value" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `switch (${ge(n.id, "val")}) {\n  ${n.f.cases || ""}\n}`,
  },
  try_catch: {
    label: "try / catch",
    cat: "control",
    col: "var(--col-flow)",
    fields: [
      { id: "try_body", label: "try body", kind: "text", def: "" },
      { id: "catch_var", label: "catch var", kind: "text", def: "err" },
      {
        id: "catch_body",
        label: "catch body",
        kind: "text",
        def: "console.error(err)",
      },
    ],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) =>
      `try {\n  ${n.f.try_body || ""}\n} catch (${n.f.catch_var || "err"}) {\n  ${n.f.catch_body || ""}\n}`,
  },
  func: {
    label: "function",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [
      { id: "name", label: "name", kind: "text", def: "myFn" },
      { id: "params", label: "params (comma sep)", kind: "text", def: "" },
    ],
    ins: [{ id: "body", label: "return value" }],
    outs: [{ id: "ref", label: "ref" }],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `function ${n.f.name || "myFn"}(${n.f.params || ""}) {\n  return ${ge(n.id, "body")};\n}`,
    ref: (n) => n.f.name || "myFn",
  },
  arrow_fn: {
    label: "arrow fn",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [
      { id: "name", label: "name", kind: "text", def: "myFn" },
      { id: "params", label: "params", kind: "text", def: "" },
    ],
    ins: [{ id: "body", label: "return value" }],
    outs: [{ id: "ref", label: "ref" }],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `const ${n.f.name || "myFn"} = (${n.f.params || ""}) => ${ge(n.id, "body")};`,
    ref: (n) => n.f.name || "myFn",
  },
  call: {
    label: "call",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [{ id: "fn", label: "function name", kind: "text", def: "myFn" }],
    ins: [
      { id: "a0", label: "arg 1" },
      { id: "a1", label: "arg 2" },
      { id: "a2", label: "arg 3" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const args = ["a0", "a1", "a2"]
        .map((a) => {
          const c = Object.values(conns).find(
            (c) => c.tn === n.id && c.tp === a,
          );
          return c ? ge(n.id, a) : null;
        })
        .filter(Boolean);
      return `${n.f.fn || "myFn"}(${args.join(", ")})`;
    },
  },
  method_call: {
    label: "method call",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [{ id: "method", label: "method", kind: "text", def: "toString" }],
    ins: [
      { id: "obj", label: "object" },
      { id: "a0", label: "arg 1" },
      { id: "a1", label: "arg 2" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const args = ["a0", "a1"]
        .map((a) => {
          const c = Object.values(conns).find(
            (c) => c.tn === n.id && c.tp === a,
          );
          return c ? ge(n.id, a) : null;
        })
        .filter(Boolean);
      return `${ge(n.id, "obj")}.${n.f.method || "toString"}(${args.join(", ")})`;
    },
  },
  ret: {
    label: "return",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `return ${ge(n.id, "val")};`,
  },
  str_concat: {
    label: "concat",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} + ${ge(n.id, "b")})`,
  },
  template_str: {
    label: "template string",
    cat: "strings",
    col: "var(--col-string)",
    fields: [
      {
        id: "tpl",
        label: "template (use $0 $1 $2)",
        kind: "text",
        def: "hello $0!",
      },
    ],
    ins: [
      { id: "v0", label: "val 1" },
      { id: "v1", label: "val 2" },
      { id: "v2", label: "val 3" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      let tpl = n.f.tpl || "";
      ["v0", "v1", "v2"].forEach((v, i) => {
        const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === v);
        if (c) tpl = tpl.replace("$" + i, "${" + ge(n.id, v) + "}");
      });
      return "`" + tpl + "`";
    },
  },
  str_length: {
    label: "length",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [{ id: "str", label: "string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.length`,
  },
  str_upper: {
    label: "to uppercase",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [{ id: "str", label: "string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.toUpperCase()`,
  },
  str_lower: {
    label: "to lowercase",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [{ id: "str", label: "string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.toLowerCase()`,
  },
  str_trim: {
    label: "trim",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [{ id: "str", label: "string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.trim()`,
  },
  str_split: {
    label: "split",
    cat: "strings",
    col: "var(--col-string)",
    fields: [{ id: "sep", label: "separator", kind: "text", def: "," }],
    ins: [{ id: "str", label: "string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.split("${n.f.sep || ","}")`,
  },
  str_includes: {
    label: "includes",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "sub", label: "substring" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.includes(${ge(n.id, "sub")})`,
  },
  str_replace: {
    label: "replace",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "from", label: "from" },
      { id: "to", label: "to" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `${ge(n.id, "str")}.replace(${ge(n.id, "from")}, ${ge(n.id, "to")})`,
  },
  str_slice: {
    label: "slice",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "start", label: "start" },
      { id: "end", label: "end" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `${ge(n.id, "str")}.slice(${ge(n.id, "start")}, ${ge(n.id, "end")})`,
  },
  arr_literal: {
    label: "array",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [
      { id: "items", label: "items (comma sep)", kind: "text", def: "1, 2, 3" },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `[${n.f.items || ""}]`,
  },
  arr_push: {
    label: "push",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "arr", label: "array" },
      { id: "val", label: "value" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `(${ge(n.id, "arr")}.push(${ge(n.id, "val")}), ${ge(n.id, "arr")})`,
  },
  arr_pop: {
    label: "pop",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.pop()`,
  },
  arr_map: {
    label: "map",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "fn", label: "callback", kind: "text", def: "x => x" }],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.map(${n.f.fn || "x => x"})`,
  },
  arr_filter: {
    label: "filter",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "fn", label: "predicate", kind: "text", def: "x => x" }],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.filter(${n.f.fn || "x => x"})`,
  },
  arr_reduce: {
    label: "reduce",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [
      { id: "fn", label: "reducer", kind: "text", def: "(acc, x) => acc + x" },
      { id: "init", label: "initial value", kind: "text", def: "0" },
    ],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `${ge(n.id, "arr")}.reduce(${n.f.fn || "(acc,x)=>acc+x"}, ${n.f.init || "0"})`,
  },
  arr_find: {
    label: "find",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "fn", label: "predicate", kind: "text", def: "x => x" }],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.find(${n.f.fn || "x => x"})`,
  },
  arr_index: {
    label: "index",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "arr", label: "array" },
      { id: "idx", label: "index" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}[${ge(n.id, "idx")}]`,
  },
  arr_length: {
    label: "length",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.length`,
  },
  arr_join: {
    label: "join",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "sep", label: "separator", kind: "text", def: ", " }],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.join("${n.f.sep || ", "}")`,
  },
  arr_slice: {
    label: "slice",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "arr", label: "array" },
      { id: "start", label: "start" },
      { id: "end", label: "end" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `${ge(n.id, "arr")}.slice(${ge(n.id, "start")}, ${ge(n.id, "end")})`,
  },
  spread: {
    label: "spread",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "a", label: "arr a" },
      { id: "b", label: "arr b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `[...${ge(n.id, "a")}, ...${ge(n.id, "b")}]`,
  },
  obj_literal: {
    label: "object",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [
      { id: "props", label: "props (raw js)", kind: "text", def: "a: 1, b: 2" },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `{ ${n.f.props || ""} }`,
  },
  obj_get: {
    label: "get prop",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [{ id: "key", label: "key", kind: "text", def: "key" }],
    ins: [{ id: "obj", label: "object" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "obj")}.${n.f.key || "key"}`,
  },
  obj_set: {
    label: "set prop",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [{ id: "key", label: "key", kind: "text", def: "key" }],
    ins: [
      { id: "obj", label: "object" },
      { id: "val", label: "value" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `${ge(n.id, "obj")}.${n.f.key || "key"} = ${ge(n.id, "val")};`,
  },
  obj_spread: {
    label: "spread merge",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [
      { id: "a", label: "obj a" },
      { id: "b", label: "obj b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `{ ...${ge(n.id, "a")}, ...${ge(n.id, "b")} }`,
  },
  obj_keys: {
    label: "keys",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "obj", label: "object" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Object.keys(${ge(n.id, "obj")})`,
  },
  obj_values: {
    label: "values",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "obj", label: "object" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Object.values(${ge(n.id, "obj")})`,
  },
  json_parse: {
    label: "JSON.parse",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [],
    ins: [{ id: "str", label: "string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `JSON.parse(${ge(n.id, "str")})`,
  },
  json_stringify: {
    label: "JSON.stringify",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [{ id: "indent", label: "indent", kind: "number", def: "2" }],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `JSON.stringify(${ge(n.id, "val")}, null, ${n.f.indent || "2"})`,
  },
  num_parse: {
    label: "parseFloat",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `parseFloat(${ge(n.id, "val")})`,
  },
  int_parse: {
    label: "parseInt",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [{ id: "radix", label: "radix", kind: "number", def: "10" }],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `parseInt(${ge(n.id, "val")}, ${n.f.radix || "10"})`,
  },
  to_string: {
    label: "toString",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `String(${ge(n.id, "val")})`,
  },
  typeof_node: {
    label: "typeof",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `typeof ${ge(n.id, "val")}`,
  },
  promise: {
    label: "new Promise",
    cat: "async",
    col: "var(--col-async)",
    fields: [
      {
        id: "resolve_val",
        label: "resolve value",
        kind: "text",
        def: "result",
      },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) =>
      `new Promise((resolve, reject) => { resolve(${n.f.resolve_val || "result"}); })`,
  },
  then: {
    label: ".then()",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "fn", label: "handler", kind: "text", def: "res => res" }],
    ins: [{ id: "promise", label: "promise" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "promise")}.then(${n.f.fn || "res => res"})`,
  },
  catch_err: {
    label: ".catch()",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "fn", label: "handler", kind: "text", def: "err => err" }],
    ins: [{ id: "promise", label: "promise" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "promise")}.catch(${n.f.fn || "err => err"})`,
  },
  await_node: {
    label: "await",
    cat: "async",
    col: "var(--col-async)",
    fields: [],
    ins: [{ id: "promise", label: "promise" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `await ${ge(n.id, "promise")}`,
  },
  fetch_node: {
    label: "fetch",
    cat: "async",
    col: "var(--col-async)",
    fields: [
      {
        id: "method",
        label: "method",
        kind: "select",
        opts: ["GET", "POST", "PUT", "DELETE", "PATCH"],
        def: "GET",
      },
    ],
    ins: [{ id: "url", label: "url" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `fetch(${ge(n.id, "url")}, { method: "${n.f.method || "GET"}" })`,
  },
  http_request: {
    label: "http request",
    cat: "async",
    col: "var(--col-async)",
    fields: [
      {
        id: "method",
        label: "method",
        kind: "select",
        opts: ["GET", "POST", "PUT", "DELETE", "PATCH"],
        def: "GET",
      },
      {
        id: "headers",
        label: "headers (json)",
        kind: "text",
        def: '{"content-type":"application/json"}',
      },
      { id: "auth", label: "bearer token", kind: "text", def: "" },
    ],
    ins: [
      { id: "url", label: "url" },
      { id: "body", label: "body" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const method = n.f.method || "GET";
      const hasBody = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "body",
      );
      let hdrs = {};
      try {
        hdrs = JSON.parse(n.f.headers || "{}");
      } catch {}
      if (n.f.auth) hdrs["authorization"] = `Bearer ${n.f.auth}`;
      const opts = [`method: "${method}"`, `headers: ${JSON.stringify(hdrs)}`];
      if (hasBody) opts.push(`body: JSON.stringify(${ge(n.id, "body")})`);
      return `fetch(${ge(n.id, "url")}, { ${opts.join(", ")} })`;
    },
  },
  set_timeout: {
    label: "setTimeout",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "fn", label: "callback", kind: "text", def: "() => {}" }],
    ins: [{ id: "delay", label: "delay ms" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `setTimeout(${n.f.fn || "() => {}"}, ${ge(n.id, "delay")});`,
  },
  query_selector: {
    label: "querySelector",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "sel", label: "selector", kind: "text", def: "#app" }],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `document.querySelector("${n.f.sel || "#app"}")`,
  },
  create_el: {
    label: "createElement",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "tag", label: "tag", kind: "text", def: "div" }],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `document.createElement("${n.f.tag || "div"}")`,
  },
  set_text: {
    label: "set textContent",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [],
    ins: [
      { id: "el", label: "element" },
      { id: "text", label: "text" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "el")}.textContent = ${ge(n.id, "text")};`,
  },
  set_attr: {
    label: "setAttribute",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "attr", label: "attribute", kind: "text", def: "class" }],
    ins: [
      { id: "el", label: "element" },
      { id: "val", label: "value" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `${ge(n.id, "el")}.setAttribute("${n.f.attr || "class"}", ${ge(n.id, "val")});`,
  },
  add_event: {
    label: "addEventListener",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [
      { id: "event", label: "event", kind: "text", def: "click" },
      { id: "fn", label: "handler", kind: "text", def: "(e) => {}" },
    ],
    ins: [{ id: "el", label: "element" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `${ge(n.id, "el")}.addEventListener("${n.f.event || "click"}", ${n.f.fn || "(e) => {}"});`,
  },
  append_child: {
    label: "appendChild",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [],
    ins: [
      { id: "parent", label: "parent" },
      { id: "child", label: "child" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "parent")}.appendChild(${ge(n.id, "child")});`,
  },
  date_now: {
    label: "Date.now()",
    cat: "date",
    col: "var(--col-date)",
    fields: [],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: () => `Date.now()`,
  },
  new_date: {
    label: "new Date",
    cat: "date",
    col: "var(--col-date)",
    fields: [],
    ins: [{ id: "val", label: "timestamp" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `new Date(${ge(n.id, "val")})`,
  },
  date_format: {
    label: "toLocaleDateString",
    cat: "date",
    col: "var(--col-date)",
    fields: [{ id: "locale", label: "locale", kind: "text", def: "en-US" }],
    ins: [{ id: "date", label: "date" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `${ge(n.id, "date")}.toLocaleDateString("${n.f.locale || "en-US"}")`,
  },
  log: {
    label: "console.log",
    cat: "output",
    col: "var(--col-out)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `console.log(${ge(n.id, "val")});`,
  },
  console_error: {
    label: "console.error",
    cat: "output",
    col: "var(--col-out)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `console.error(${ge(n.id, "val")});`,
  },
  alert_node: {
    label: "alert",
    cat: "output",
    col: "var(--col-out)",
    fields: [],
    ins: [{ id: "val", label: "message" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `alert(${ge(n.id, "val")});`,
  },
  comment: {
    label: "comment",
    cat: "output",
    col: "var(--col-out)",
    fields: [{ id: "text", label: "text", kind: "text", def: "note here" }],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => `// ${n.f.text || ""}`,
  },
  raw_js: {
    label: "raw js",
    cat: "output",
    col: "var(--col-out)",
    fields: [{ id: "code", label: "code", kind: "text", def: "" }],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => n.f.code || "",
  },
  typeof_in_stmt: {
    label: "typeof (stmt)",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `typeof ${ge(n.id, "val")}`,
  },
  instanceof: {
    label: "instanceof",
    cat: "logic",
    col: "var(--col-logic)",
    fields: [{ id: "cls", label: "class", kind: "text", def: "Array" }],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "val")} instanceof ${n.f.cls || "Array"})`,
  },
  in_op: {
    label: "in",
    cat: "logic",
    col: "var(--col-logic)",
    fields: [{ id: "key", label: "key", kind: "text", def: "prop" }],
    ins: [{ id: "obj", label: "object" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `("${n.f.key}" in ${ge(n.id, "obj")})`,
  },
  bitand: {
    label: "bitwise &",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} & ${ge(n.id, "b")})`,
  },
  bitor: {
    label: "bitwise |",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} | ${ge(n.id, "b")})`,
  },
  bitxor: {
    label: "bitwise ^",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} ^ ${ge(n.id, "b")})`,
  },
  bitnot: {
    label: "bitwise ~",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(~${ge(n.id, "a")})`,
  },
  lshift: {
    label: "left shift",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} << ${ge(n.id, "b")})`,
  },
  rshift: {
    label: "right shift",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} >> ${ge(n.id, "b")})`,
  },
  urshift: {
    label: ">>> shift",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} >>> ${ge(n.id, "b")})`,
  },
  sqrt: {
    label: "sqrt",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.sqrt(${ge(n.id, "a")})`,
  },
  log_math: {
    label: "log",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.log(${ge(n.id, "a")})`,
  },
  sin: {
    label: "sin",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "radians" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.sin(${ge(n.id, "a")})`,
  },
  cos: {
    label: "cos",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "radians" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.cos(${ge(n.id, "a")})`,
  },
  tan: {
    label: "tan",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "radians" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.tan(${ge(n.id, "a")})`,
  },
  pi: {
    label: "Math.PI",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: () => `Math.PI`,
  },
  infinity: {
    label: "Infinity",
    cat: "values",
    col: "var(--col-val)",
    fields: [],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: () => `Infinity`,
  },
  nan_val: {
    label: "NaN",
    cat: "values",
    col: "var(--col-val)",
    fields: [],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: () => `NaN`,
  },
  isnan: {
    label: "isNaN",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `isNaN(${ge(n.id, "val")})`,
  },
  isfinite: {
    label: "isFinite",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `isFinite(${ge(n.id, "val")})`,
  },
  number_cast: {
    label: "Number()",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Number(${ge(n.id, "val")})`,
  },
  bool_cast: {
    label: "Boolean()",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Boolean(${ge(n.id, "val")})`,
  },
  arr_includes: {
    label: "includes",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "arr", label: "array" },
      { id: "val", label: "value" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.includes(${ge(n.id, "val")})`,
  },
  arr_indexof: {
    label: "indexOf",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "arr", label: "array" },
      { id: "val", label: "value" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.indexOf(${ge(n.id, "val")})`,
  },
  arr_map: {
    label: "map",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "fn", label: "fn (or wire)", kind: "text", def: "x => x" }],
    ins: [
      { id: "arr", label: "array" },
      { id: "fn_port", label: "fn (wired)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const wired = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "fn_port",
      );
      return `${ge(n.id, "arr")}.map(${wired ? ge(n.id, "fn_port") : n.f.fn || "x => x"})`;
    },
  },
  arr_filter: {
    label: "filter",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [
      { id: "fn", label: "predicate (or wire)", kind: "text", def: "x => x" },
    ],
    ins: [
      { id: "arr", label: "array" },
      { id: "fn_port", label: "fn (wired)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const wired = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "fn_port",
      );
      return `${ge(n.id, "arr")}.filter(${wired ? ge(n.id, "fn_port") : n.f.fn || "x => x"})`;
    },
  },
  arr_find: {
    label: "find",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [
      { id: "fn", label: "predicate (or wire)", kind: "text", def: "x => x" },
    ],
    ins: [
      { id: "arr", label: "array" },
      { id: "fn_port", label: "fn (wired)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const wired = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "fn_port",
      );
      return `${ge(n.id, "arr")}.find(${wired ? ge(n.id, "fn_port") : n.f.fn || "x => x"})`;
    },
  },
  arr_reduce: {
    label: "reduce",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [
      {
        id: "fn",
        label: "reducer (or wire)",
        kind: "text",
        def: "(acc, x) => acc + x",
      },
      { id: "init", label: "initial value", kind: "text", def: "0" },
    ],
    ins: [
      { id: "arr", label: "array" },
      { id: "fn_port", label: "fn (wired)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const wired = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "fn_port",
      );
      return `${ge(n.id, "arr")}.reduce(${wired ? ge(n.id, "fn_port") : n.f.fn || "(acc,x)=>acc+x"}, ${n.f.init || "0"})`;
    },
  },
  arr_flatmap: {
    label: "flatmap",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [
      { id: "fn", label: "callback (or wire)", kind: "text", def: "x => x" },
    ],
    ins: [
      { id: "arr", label: "array" },
      { id: "fn_port", label: "fn (wired)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const wired = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "fn_port",
      );
      return `${ge(n.id, "arr")}.flatMap(${wired ? ge(n.id, "fn_port") : n.f.fn || "x => x"})`;
    },
  },
  arr_every: {
    label: "every",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [
      { id: "fn", label: "predicate (or wire)", kind: "text", def: "x => x" },
    ],
    ins: [
      { id: "arr", label: "array" },
      { id: "fn_port", label: "fn (wired)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const wired = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "fn_port",
      );
      return `${ge(n.id, "arr")}.every(${wired ? ge(n.id, "fn_port") : n.f.fn || "x => x"})`;
    },
  },
  arr_some: {
    label: "some",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [
      { id: "fn", label: "predicate (or wire)", kind: "text", def: "x => x" },
    ],
    ins: [
      { id: "arr", label: "array" },
      { id: "fn_port", label: "fn (wired)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const wired = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "fn_port",
      );
      return `${ge(n.id, "arr")}.some(${wired ? ge(n.id, "fn_port") : n.f.fn || "x => x"})`;
    },
  },
  arr_sort: {
    label: "sort",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "fn", label: "comparator", kind: "text", def: "" }],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      n.f.fn
        ? `${ge(n.id, "arr")}.sort(${n.f.fn})`
        : `${ge(n.id, "arr")}.sort()`,
  },
  arr_reverse: {
    label: "reverse",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.reverse()`,
  },
  arr_concat: {
    label: "concat",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "a", label: "arr a" },
      { id: "b", label: "arr b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "a")}.concat(${ge(n.id, "b")})`,
  },
  arr_fill: {
    label: "fill",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "arr", label: "array" },
      { id: "val", label: "value" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.fill(${ge(n.id, "val")})`,
  },
  arr_from: {
    label: "Array.from",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [{ id: "val", label: "iterable" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Array.from(${ge(n.id, "val")})`,
  },
  arr_isarray: {
    label: "Array.isArray",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Array.isArray(${ge(n.id, "val")})`,
  },
  obj_assign: {
    label: "Object.assign",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [
      { id: "a", label: "target" },
      { id: "b", label: "source" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Object.assign(${ge(n.id, "a")}, ${ge(n.id, "b")})`,
  },
  obj_entries: {
    label: "entries",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "obj", label: "object" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Object.entries(${ge(n.id, "obj")})`,
  },
  obj_freeze: {
    label: "Object.freeze",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "obj", label: "object" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Object.freeze(${ge(n.id, "obj")})`,
  },
  obj_has: {
    label: "hasOwn",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [{ id: "key", label: "key", kind: "text", def: "prop" }],
    ins: [{ id: "obj", label: "object" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Object.hasOwn(${ge(n.id, "obj")}, "${n.f.key}")`,
  },
  destructure: {
    label: "destructure",
    cat: "variables",
    col: "var(--col-var)",
    fields: [
      { id: "keys", label: "keys (comma sep)", kind: "text", def: "a, b" },
      {
        id: "kind",
        label: "kind",
        kind: "select",
        opts: ["const", "let", "var"],
        def: "const",
      },
    ],
    ins: [{ id: "obj", label: "object" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `${n.f.kind || "const"} { ${n.f.keys || "a, b"} } = ${ge(n.id, "obj")};`,
  },
  arr_destructure: {
    label: "arr destructure",
    cat: "variables",
    col: "var(--col-var)",
    fields: [
      { id: "vars", label: "vars (comma sep)", kind: "text", def: "a, b" },
      {
        id: "kind",
        label: "kind",
        kind: "select",
        opts: ["const", "let", "var"],
        def: "const",
      },
    ],
    ins: [{ id: "arr", label: "array" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `${n.f.kind || "const"} [ ${n.f.vars || "a, b"} ] = ${ge(n.id, "arr")};`,
  },
  optional_chain: {
    label: "optional ?.",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [{ id: "path", label: "path", kind: "text", def: "prop" }],
    ins: [{ id: "obj", label: "object" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "obj")}?.${n.f.path || "prop"}`,
  },
  new_set: {
    label: "new Set",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [{ id: "arr", label: "iterable" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `new Set(${ge(n.id, "arr")})`,
  },
  new_map: {
    label: "new Map",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "arr", label: "entries" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `new Map(${ge(n.id, "arr")})`,
  },
  set_interval: {
    label: "setInterval",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "fn", label: "callback", kind: "text", def: "() => {}" }],
    ins: [{ id: "delay", label: "interval ms" }],
    outs: [{ id: "out", label: "id" }],
    expr: true,
    gen: (n, ge) =>
      `setInterval(${n.f.fn || "() => {}"}, ${ge(n.id, "delay")})`,
  },
  clear_timeout: {
    label: "clearTimeout",
    cat: "async",
    col: "var(--col-async)",
    fields: [],
    ins: [{ id: "id", label: "timer id" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `clearTimeout(${ge(n.id, "id")});`,
  },
  clear_interval: {
    label: "clearInterval",
    cat: "async",
    col: "var(--col-async)",
    fields: [],
    ins: [{ id: "id", label: "timer id" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `clearInterval(${ge(n.id, "id")});`,
  },
  promise_all: {
    label: "Promise.all",
    cat: "async",
    col: "var(--col-async)",
    fields: [],
    ins: [{ id: "arr", label: "promises" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Promise.all(${ge(n.id, "arr")})`,
  },
  promise_race: {
    label: "Promise.race",
    cat: "async",
    col: "var(--col-async)",
    fields: [],
    ins: [{ id: "arr", label: "promises" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Promise.race(${ge(n.id, "arr")})`,
  },
  promise_resolve: {
    label: "Promise.resolve",
    cat: "async",
    col: "var(--col-async)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Promise.resolve(${ge(n.id, "val")})`,
  },
  async_fn: {
    label: "async fn",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [
      { id: "name", label: "name", kind: "text", def: "myFn" },
      { id: "params", label: "params", kind: "text", def: "" },
    ],
    ins: [{ id: "body", label: "return value" }],
    outs: [{ id: "ref", label: "ref" }],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `async function ${n.f.name || "myFn"}(${n.f.params || ""}) {\n  return ${ge(n.id, "body")};\n}`,
    ref: (n) => n.f.name || "myFn",
  },
  iife: {
    label: "iife",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [{ id: "body", label: "body", kind: "text", def: "" }],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => `(function() {\n  ${n.f.body || ""}\n})();`,
  },
  spread_args: {
    label: "...spread args",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `...${ge(n.id, "arr")}`,
  },
  str_charat: {
    label: "charAt",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "idx", label: "index" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.charAt(${ge(n.id, "idx")})`,
  },
  str_indexof: {
    label: "indexOf",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "sub", label: "substring" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.indexOf(${ge(n.id, "sub")})`,
  },
  str_startswith: {
    label: "startsWith",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "sub", label: "prefix" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.startsWith(${ge(n.id, "sub")})`,
  },
  str_endswith: {
    label: "endsWith",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "sub", label: "suffix" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.endsWith(${ge(n.id, "sub")})`,
  },
  str_padstart: {
    label: "padStart",
    cat: "strings",
    col: "var(--col-string)",
    fields: [
      { id: "len", label: "length", kind: "number", def: "2" },
      { id: "ch", label: "pad char", kind: "text", def: "0" },
    ],
    ins: [{ id: "str", label: "string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `${ge(n.id, "str")}.padStart(${n.f.len || 2}, "${n.f.ch || "0"}")`,
  },
  str_padend: {
    label: "padEnd",
    cat: "strings",
    col: "var(--col-string)",
    fields: [
      { id: "len", label: "length", kind: "number", def: "2" },
      { id: "ch", label: "pad char", kind: "text", def: " " },
    ],
    ins: [{ id: "str", label: "string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `${ge(n.id, "str")}.padEnd(${n.f.len || 2}, "${n.f.ch || " "}")`,
  },
  str_repeat: {
    label: "repeat",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "n", label: "count" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.repeat(${ge(n.id, "n")})`,
  },
  str_match: {
    label: "match",
    cat: "strings",
    col: "var(--col-string)",
    fields: [{ id: "re", label: "regex", kind: "text", def: "/pattern/g" }],
    ins: [{ id: "str", label: "string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.match(${n.f.re || "/pattern/g"})`,
  },
  regex_test: {
    label: "regex tester",
    cat: "strings",
    col: "var(--col-string)",
    fields: [
      { id: "pattern", label: "pattern", kind: "text", def: "\\w+" },
      { id: "flags", label: "flags", kind: "text", def: "gi" },
      {
        id: "test",
        label: "test string",
        kind: "text",
        def: "hello world 123",
      },
    ],
    ins: [{ id: "str", label: "string (optional)" }],
    outs: [{ id: "out", label: "matches" }],
    expr: true,
    gen: (n, ge) => {
      const p = (n.f.pattern || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      const c = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "str",
      );
      const src = c
        ? ge(n.id, "str")
        : `"${(n.f.test || "").replace(/"/g, '\\"')}"`;
      return `${src}.match(new RegExp("${p}", "${n.f.flags || "gi"}"))`;
    },
    postRender: (wrap, n) => {
      const prev = document.createElement("div");
      prev.style.cssText =
        "padding:5px 10px 9px;border-top:1px solid var(--b1);font-family:'DM Mono',monospace;font-size:10px;line-height:1.5;word-break:break-all;min-height:24px;";
      wrap.querySelector(".nbody").appendChild(prev);
      function run() {
        const pat = n.f.pattern || "";
        const str = n.f.test || "";
        if (!pat || !str) {
          prev.textContent = "";
          return;
        }
        try {
          const flags = (n.f.flags || "gi").includes("g")
            ? n.f.flags
            : (n.f.flags || "") + "g";
          const matches = [...str.matchAll(new RegExp(pat, flags))].map(
            (m) => m[0],
          );
          prev.style.color = matches.length
            ? "var(--col-string)"
            : "var(--cream3)";
          prev.textContent = matches.length
            ? `${matches.length} match${matches.length !== 1 ? "es" : ""}: ${matches.slice(0, 5).join(" · ")}${matches.length > 5 ? ` +${matches.length - 5}` : ""}`
            : "no matches";
        } catch {
          prev.style.color = "var(--col-flow)";
          prev.textContent = "invalid pattern";
        }
      }
      wrap
        .querySelectorAll(".nfinput")
        .forEach((i) => i.addEventListener("input", run));
      run();
    },
  },
  str_replaceall: {
    label: "replaceAll",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "from", label: "from" },
      { id: "to", label: "to" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `${ge(n.id, "str")}.replaceAll(${ge(n.id, "from")}, ${ge(n.id, "to")})`,
  },
  query_all: {
    label: "querySelectorAll",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "sel", label: "selector", kind: "text", def: ".item" }],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `document.querySelectorAll("${n.f.sel || ".item"}")`,
  },
  get_attr: {
    label: "getAttribute",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "attr", label: "attribute", kind: "text", def: "class" }],
    ins: [{ id: "el", label: "element" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "el")}.getAttribute("${n.f.attr || "class"}")`,
  },
  remove_el: {
    label: "remove",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [],
    ins: [{ id: "el", label: "element" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "el")}.remove();`,
  },
  class_add: {
    label: "classList.add",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "cls", label: "class", kind: "text", def: "active" }],
    ins: [{ id: "el", label: "element" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `${ge(n.id, "el")}.classList.add("${n.f.cls || "active"}");`,
  },
  class_remove: {
    label: "classList.remove",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "cls", label: "class", kind: "text", def: "active" }],
    ins: [{ id: "el", label: "element" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `${ge(n.id, "el")}.classList.remove("${n.f.cls || "active"}");`,
  },
  class_toggle: {
    label: "classList.toggle",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "cls", label: "class", kind: "text", def: "active" }],
    ins: [{ id: "el", label: "element" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `${ge(n.id, "el")}.classList.toggle("${n.f.cls || "active"}");`,
  },
  set_style: {
    label: "set style",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "prop", label: "property", kind: "text", def: "color" }],
    ins: [
      { id: "el", label: "element" },
      { id: "val", label: "value" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `${ge(n.id, "el")}.style["${n.f.prop || "color"}"] = ${ge(n.id, "val")};`,
  },
  inner_html: {
    label: "innerHTML",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [],
    ins: [
      { id: "el", label: "element" },
      { id: "html", label: "html string" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "el")}.innerHTML = ${ge(n.id, "html")};`,
  },
  local_storage_get: {
    label: "localStorage.get",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "key", label: "key", kind: "text", def: "myKey" }],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `localStorage.getItem("${n.f.key || "myKey"}")`,
  },
  local_storage_set: {
    label: "localStorage.set",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "key", label: "key", kind: "text", def: "myKey" }],
    ins: [{ id: "val", label: "value" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `localStorage.setItem("${n.f.key || "myKey"}", ${ge(n.id, "val")});`,
  },
  console_table: {
    label: "console.table",
    cat: "output",
    col: "var(--col-out)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `console.table(${ge(n.id, "val")});`,
  },
  console_warn: {
    label: "console.warn",
    cat: "output",
    col: "var(--col-out)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `console.warn(${ge(n.id, "val")});`,
  },
  throw_node: {
    label: "throw",
    cat: "control",
    col: "var(--col-flow)",
    fields: [{ id: "msg", label: "message", kind: "text", def: "error" }],
    ins: [{ id: "val", label: "value (optional)" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => {
      const c = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "val",
      );
      return c
        ? `throw ${ge(n.id, "val")};`
        : `throw new Error("${n.f.msg || "error"}");`;
    },
  },
  break_node: {
    label: "break",
    cat: "control",
    col: "var(--col-flow)",
    fields: [],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: () => `break;`,
  },
  continue_node: {
    label: "continue",
    cat: "control",
    col: "var(--col-flow)",
    fields: [],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: () => `continue;`,
  },
  for_of: {
    label: "for...of",
    cat: "control",
    col: "var(--col-flow)",
    fields: [
      { id: "item", label: "item var", kind: "text", def: "item" },
      { id: "body", label: "body", kind: "text", def: "console.log(item)" },
    ],
    ins: [{ id: "iter", label: "iterable" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `for (const ${n.f.item || "item"} of ${ge(n.id, "iter")}) {\n  ${n.f.body || ""}\n}`,
  },
  for_in: {
    label: "for...in",
    cat: "control",
    col: "var(--col-flow)",
    fields: [
      { id: "key", label: "key var", kind: "text", def: "key" },
      { id: "body", label: "body", kind: "text", def: "console.log(key)" },
    ],
    ins: [{ id: "obj", label: "object" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `for (const ${n.f.key || "key"} in ${ge(n.id, "obj")}) {\n  ${n.f.body || ""}\n}`,
  },
  do_while: {
    label: "do...while",
    cat: "control",
    col: "var(--col-flow)",
    fields: [{ id: "body", label: "body", kind: "text", def: "" }],
    ins: [{ id: "cond", label: "condition" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `do {\n  ${n.f.body || ""}\n} while (${ge(n.id, "cond")});`,
  },
  label_stmt: {
    label: "labeled stmt",
    cat: "control",
    col: "var(--col-flow)",
    fields: [
      { id: "lbl", label: "label", kind: "text", def: "outer" },
      { id: "body", label: "body", kind: "text", def: "" },
    ],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => `${n.f.lbl || "outer"}: {\n  ${n.f.body || ""}\n}`,
  },
  subgraph: {
    label: "subgraph / macro",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [
      { id: "name", label: "name", kind: "text", def: "macro" },
      { id: "code", label: "body (raw js)", kind: "text", def: "" },
    ],
    ins: [
      { id: "a0", label: "in 1" },
      { id: "a1", label: "in 2" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: false,
    stmt: true,
    gen: (n, ge) => {
      const c0 = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "a0",
      );
      const c1 = Object.values(conns).find(
        (c) => c.tn === n.id && c.tp === "a1",
      );
      return `(function ${n.f.name || "macro"}(${c0 ? "__a0" : ""}, ${c1 ? "__a1" : ""}) {\n  ${n.f.code || ""}\n})(${c0 ? ge(n.id, "a0") : ""}${c0 && c1 ? ", " : ""}${c1 ? ge(n.id, "a1") : ""})`;
    },
  },
  arr_findindex: {
    label: "findindex",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "fn", label: "predicate", kind: "text", def: "x => x" }],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.findIndex(${n.f.fn || "x => x"})`,
  },
  arr_findlast: {
    label: "findlast",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "fn", label: "predicate", kind: "text", def: "x => x" }],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.findLast(${n.f.fn || "x => x"})`,
  },
  arr_at: {
    label: "arr.at()",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "arr", label: "array" },
      { id: "idx", label: "index" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.at(${ge(n.id, "idx")})`,
  },
  arr_shift: {
    label: "shift",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.shift()`,
  },
  arr_unshift: {
    label: "unshift",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "arr", label: "array" },
      { id: "val", label: "value" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `(${ge(n.id, "arr")}.unshift(${ge(n.id, "val")}), ${ge(n.id, "arr")})`,
  },
  arr_splice: {
    label: "splice",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [
      { id: "start", label: "start", kind: "number", def: "0" },
      { id: "deleteCount", label: "delete count", kind: "number", def: "1" },
    ],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "removed" }],
    expr: true,
    gen: (n, ge) =>
      `${ge(n.id, "arr")}.splice(${n.f.start || "0"}, ${n.f.deleteCount || "1"})`,
  },
  arr_of: {
    label: "array.of",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "v0", label: "val 1" },
      { id: "v1", label: "val 2" },
      { id: "v2", label: "val 3" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const args = ["v0", "v1", "v2"]
        .filter((v) =>
          Object.values(conns).find((c) => c.tn === n.id && c.tp === v),
        )
        .map((v) => ge(n.id, v));
      return `Array.of(${args.join(", ")})`;
    },
  },
  str_at: {
    label: "str.at()",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "idx", label: "index" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.at(${ge(n.id, "idx")})`,
  },
  str_trimstart: {
    label: "trimstart",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [{ id: "str", label: "string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.trimStart()`,
  },
  str_trimend: {
    label: "trimend",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [{ id: "str", label: "string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.trimEnd()`,
  },
  str_fromcharcode: {
    label: "string.fromcharcode",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [{ id: "code", label: "char code" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `String.fromCharCode(${ge(n.id, "code")})`,
  },
  str_charcodeat: {
    label: "charcodeat",
    cat: "strings",
    col: "var(--col-string)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "idx", label: "index" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.charCodeAt(${ge(n.id, "idx")})`,
  },
  num_tofixed: {
    label: "tofixed",
    cat: "math",
    col: "var(--col-math)",
    fields: [{ id: "digits", label: "digits", kind: "number", def: "2" }],
    ins: [{ id: "val", label: "number" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "val")}).toFixed(${n.f.digits ?? "2"})`,
  },
  math_sign: {
    label: "math.sign",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.sign(${ge(n.id, "a")})`,
  },
  math_trunc: {
    label: "math.trunc",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "a", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.trunc(${ge(n.id, "a")})`,
  },
  math_hypot: {
    label: "math.hypot",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.hypot(${ge(n.id, "a")}, ${ge(n.id, "b")})`,
  },
  math_clamp: {
    label: "clamp",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "val", label: "value" },
      { id: "min", label: "min" },
      { id: "max", label: "max" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) =>
      `Math.min(Math.max(${ge(n.id, "val")}, ${ge(n.id, "min")}), ${ge(n.id, "max")})`,
  },
  structured_clone: {
    label: "structuredclone",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `structuredClone(${ge(n.id, "val")})`,
  },
  obj_fromEntries: {
    label: "object.fromentries",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "entries", label: "entries" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Object.fromEntries(${ge(n.id, "entries")})`,
  },
  symbol_node: {
    label: "symbol",
    cat: "values",
    col: "var(--col-val)",
    fields: [{ id: "desc", label: "description", kind: "text", def: "" }],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => (n.f.desc ? `Symbol("${n.f.desc}")` : `Symbol()`),
  },
  performance_now: {
    label: "performance.now()",
    cat: "date",
    col: "var(--col-date)",
    fields: [],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: () => `performance.now()`,
  },
  console_log_multi: {
    label: "console.log (multi)",
    cat: "output",
    col: "var(--col-out)",
    fields: [],
    ins: [
      { id: "v0", label: "val 1" },
      { id: "v1", label: "val 2" },
      { id: "v2", label: "val 3" },
      { id: "v3", label: "val 4" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => {
      const args = ["v0", "v1", "v2", "v3"]
        .filter((v) =>
          Object.values(conns).find((c) => c.tn === n.id && c.tp === v),
        )
        .map((v) => ge(n.id, v));
      return `console.log(${args.join(", ")});`;
    },
  },
  asset_ref: {
    label: "asset",
    cat: "assets",
    col: "var(--col-async)",
    fields: [{ id: "id", label: "asset id", kind: "text", def: "" }],
    ins: [],
    outs: [{ id: "url", label: "data url" }],
    expr: true,
    gen: (n) => `(__assets && __assets["${n.f.id}"]?.data || "")`,
    postRender: (wrap, n) => {
      const preview = document.createElement("div");
      preview.style.cssText =
        "padding:4px 9px 8px;border-top:1px solid var(--b1);min-height:22px;";
      function refreshPreview(id) {
        preview.innerHTML = "";
        const a = assetCache[id];
        if (!a) {
          preview.innerHTML = `<span style="font-size:9px;color:var(--cream3)">paste id from assets panel</span>`;
          return;
        }
        if (a.kind === "image") {
          const img = document.createElement("img");
          img.src = a.data;
          img.style.cssText =
            "width:100%;max-height:68px;object-fit:cover;border-radius:5px;cursor:pointer;";
          img.onclick = () => openAssetViewer(a);
          preview.appendChild(img);
        } else {
          const icons = { audio: "🎵", video: "🎬", text: "📄", other: "📎" };
          preview.innerHTML = `<span style="font-size:10px;color:var(--cream2)">${icons[a.kind] || "📎"} ${a.name}</span>`;
        }
      }
      refreshPreview(n.f.id);
      wrap.querySelector(".nbody").appendChild(preview);
      wrap.querySelectorAll(".nfinput").forEach((inp) =>
        inp.addEventListener("input", (e) => {
          n.f.id = e.target.value;
          refreshPreview(e.target.value);
        }),
      );
    },
  },
  html_viewer: {
    label: "html viewer",
    cat: "assets",
    col: "var(--col-dom)",
    fields: [],
    ins: [{ id: "html", label: "html string" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) =>
      `(typeof __showHtmlPreview === "function" ? __showHtmlPreview : (h) => console.log("[html preview]", h))(${ge(n.id, "html")});`,
  },
  entry: {
    label: "▶ start",
    cat: "control",
    col: "#ffffff",
    fields: [],
    ins: [],
    outs: [],
    execOuts: [{ id: "out", label: "then" }],
    expr: false,
    stmt: false,
    gen: () => "",
  },
  exec_if: {
    label: "if (exec)",
    cat: "control",
    col: "var(--col-flow)",
    fields: [],
    ins: [{ id: "cond", label: "condition" }],
    outs: [],
    execOuts: [
      { id: "then", label: "then" },
      { id: "else", label: "else" },
    ],
    expr: false,
    stmt: false,
    gen: () => "",
  },
};
