const TYPES_ADDITIONS = {
  html_tag: {
    label: "html tag",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      { id: "tag", label: "tag", kind: "text", def: "div" },
      { id: "attrs", label: "attributes", kind: "text", def: "" },
    ],
    ins: [{ id: "content", label: "content" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const attrs = n.f.attrs ? " " + n.f.attrs : "";
      const tag = n.f.tag || "div";
      const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === "content");
      const inner = c ? "${" + ge(n.id, "content") + "}" : "";
      return "`<${tag}${attrs}>${inner}</${tag}>`".replace("${tag}", tag).replace("${tag}", tag).replace("${attrs}", attrs).replace("${inner}", inner);
    },
  },
  html_element: {
    label: "html element",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      { id: "tag", label: "tag", kind: "text", def: "div" },
      { id: "attrs", label: "attributes", kind: "text", def: "" },
      { id: "content", label: "inner content", kind: "text", def: "" },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => {
      const attrs = n.f.attrs ? " " + n.f.attrs : "";
      return `"<${n.f.tag || "div"}${attrs}>${n.f.content || ""}</${n.f.tag || "div"}>"`;
    },
  },
  html_void: {
    label: "void element",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      {
        id: "tag",
        label: "tag",
        kind: "select",
        opts: ["img", "input", "br", "hr", "meta", "link", "source", "track", "wbr"],
        def: "img",
      },
      { id: "attrs", label: "attributes", kind: "text", def: 'src="" alt=""' },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => {
      const attrs = n.f.attrs ? " " + n.f.attrs : "";
      return `"<${n.f.tag || "img"}${attrs}>"`;
    },
  },
  html_template: {
    label: "html template",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      {
        id: "tpl",
        label: "template (use $0 $1 $2)",
        kind: "text",
        def: "<div class='box'>$0</div>",
      },
    ],
    ins: [
      { id: "v0", label: "val 1" },
      { id: "v1", label: "val 2" },
      { id: "v2", label: "val 3" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      let tpl = n.f.tpl || "";
      ["v0", "v1", "v2"].forEach((v, i) => {
        const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === v);
        if (c) tpl = tpl.replace("$" + i, "${" + ge(n.id, v) + "}");
      });
      return "`" + tpl + "`";
    },
  },
  html_concat: {
    label: "html concat",
    cat: "html",
    col: "var(--col-html)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} + ${ge(n.id, "b")})`,
  },
  html_wrap: {
    label: "wrap in tag",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      { id: "tag", label: "tag", kind: "text", def: "div" },
      { id: "cls", label: "class", kind: "text", def: "" },
      { id: "id", label: "id", kind: "text", def: "" },
    ],
    ins: [{ id: "content", label: "content" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const tag = n.f.tag || "div";
      const cls = n.f.cls ? ` class="${n.f.cls}"` : "";
      const id = n.f.id ? ` id="${n.f.id}"` : "";
      return `\`<${tag}${id}${cls}>\${${ge(n.id, "content")}}</${tag}>\``;
    },
  },
  html_list: {
    label: "html list",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      {
        id: "type",
        label: "type",
        kind: "select",
        opts: ["ul", "ol"],
        def: "ul",
      },
      { id: "cls", label: "class", kind: "text", def: "" },
    ],
    ins: [{ id: "items", label: "items array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const tag = n.f.type || "ul";
      const cls = n.f.cls ? ` class="${n.f.cls}"` : "";
      return `\`<${tag}${cls}>\${${ge(n.id, "items")}.map(i => \`<li>\${i}</li>\`).join("")}</${tag}>\``;
    },
  },
  html_table: {
    label: "html table",
    cat: "html",
    col: "var(--col-html)",
    fields: [{ id: "cls", label: "class", kind: "text", def: "" }],
    ins: [
      { id: "headers", label: "headers array" },
      { id: "rows", label: "rows (2d array)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const cls = n.f.cls ? ` class="${n.f.cls}"` : "";
      return `\`<table${cls}><thead><tr>\${${ge(n.id, "headers")}.map(h => \`<th>\${h}</th>\`).join("")}</tr></thead><tbody>\${${ge(n.id, "rows")}.map(r => \`<tr>\${r.map(c => \`<td>\${c}</td>\`).join("")}</tr>\`).join("")}</tbody></table>\``;
    },
  },
  html_form: {
    label: "html form",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      { id: "action", label: "action", kind: "text", def: "" },
      {
        id: "method",
        label: "method",
        kind: "select",
        opts: ["post", "get"],
        def: "post",
      },
    ],
    ins: [{ id: "content", label: "content" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const action = n.f.action ? ` action="${n.f.action}"` : "";
      return `\`<form${action} method="${n.f.method || "post"}">\${${ge(n.id, "content")}}</form>\``;
    },
  },
  html_input: {
    label: "html input",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      {
        id: "type",
        label: "type",
        kind: "select",
        opts: ["text", "number", "email", "password", "checkbox", "radio", "range", "color", "file", "submit", "button"],
        def: "text",
      },
      { id: "name", label: "name", kind: "text", def: "field" },
      { id: "placeholder", label: "placeholder", kind: "text", def: "" },
      { id: "attrs", label: "extra attrs", kind: "text", def: "" },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => {
      const ph = n.f.placeholder ? ` placeholder="${n.f.placeholder}"` : "";
      const extra = n.f.attrs ? " " + n.f.attrs : "";
      return `"<input type=\\"${n.f.type || "text"}\\" name=\\"${n.f.name || "field"}\\"${ph}${extra}>"`;
    },
  },
  html_link: {
    label: "html link",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      { id: "href", label: "href", kind: "text", def: "#" },
      { id: "text", label: "text", kind: "text", def: "click here" },
      { id: "target", label: "target", kind: "text", def: "" },
    ],
    ins: [{ id: "href_in", label: "href (wired)" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === "href_in");
      const href = c ? `\${${ge(n.id, "href_in")}}` : (n.f.href || "#");
      const target = n.f.target ? ` target="${n.f.target}"` : "";
      return `\`<a href="${href}"${target}>${n.f.text || "click here"}</a>\``;
    },
  },
  html_img: {
    label: "html img",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      { id: "src", label: "src", kind: "text", def: "" },
      { id: "alt", label: "alt", kind: "text", def: "" },
      { id: "attrs", label: "extra attrs", kind: "text", def: "" },
    ],
    ins: [{ id: "src_in", label: "src (wired)" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === "src_in");
      const src = c ? `\${${ge(n.id, "src_in")}}` : (n.f.src || "");
      const extra = n.f.attrs ? " " + n.f.attrs : "";
      return `\`<img src="${src}" alt="${n.f.alt || ""}"${extra}>\``;
    },
  },
  html_script: {
    label: "html script",
    cat: "html",
    col: "var(--col-html)",
    fields: [{ id: "code", label: "js code", kind: "text", def: "console.log('hi')" }],
    ins: [{ id: "code_in", label: "code (wired)" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === "code_in");
      const code = c ? `\${${ge(n.id, "code_in")}}` : (n.f.code || "");
      return `\`<script>${code}<\/script>\``;
    },
  },
  html_style: {
    label: "html style",
    cat: "html",
    col: "var(--col-html)",
    fields: [{ id: "css", label: "css", kind: "text", def: "body { margin: 0; }" }],
    ins: [{ id: "css_in", label: "css (wired)" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === "css_in");
      const css = c ? `\${${ge(n.id, "css_in")}}` : (n.f.css || "");
      return `\`<style>${css}</style>\``;
    },
  },
  html_page: {
    label: "full html page",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      { id: "title", label: "title", kind: "text", def: "page" },
      { id: "head_extra", label: "extra head", kind: "text", def: "" },
    ],
    ins: [
      { id: "styles", label: "styles" },
      { id: "body", label: "body content" },
      { id: "scripts", label: "scripts" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const cs = Object.values(conns).find((c) => c.tn === n.id && c.tp === "styles");
      const cb = Object.values(conns).find((c) => c.tn === n.id && c.tp === "body");
      const csc = Object.values(conns).find((c) => c.tn === n.id && c.tp === "scripts");
      const styles = cs ? `\${${ge(n.id, "styles")}}` : "";
      const body = cb ? `\${${ge(n.id, "body")}}` : "";
      const scripts = csc ? `\${${ge(n.id, "scripts")}}` : "";
      const extra = n.f.head_extra || "";
      return `\`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${n.f.title || "page"}</title>${extra}${styles}</head><body>${body}${scripts}</body></html>\``;
    },
  },
  html_map_to_tags: {
    label: "map to tags",
    cat: "html",
    col: "var(--col-html)",
    fields: [
      { id: "tag", label: "tag", kind: "text", def: "div" },
      { id: "cls", label: "class", kind: "text", def: "" },
    ],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const cls = n.f.cls ? ` class="${n.f.cls}"` : "";
      const tag = n.f.tag || "div";
      return `${ge(n.id, "arr")}.map(item => \`<${tag}${cls}>\${item}</${tag}>\`).join("")`;
    },
  },
  css_rule: {
    label: "css rule",
    cat: "css",
    col: "var(--col-css)",
    fields: [
      { id: "selector", label: "selector", kind: "text", def: ".box" },
      { id: "props", label: "properties", kind: "text", def: "color: red;" },
    ],
    ins: [
      { id: "selector_in", label: "selector (wired)" },
      { id: "props_in", label: "props (wired)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const cs = Object.values(conns).find((c) => c.tn === n.id && c.tp === "selector_in");
      const cp = Object.values(conns).find((c) => c.tn === n.id && c.tp === "props_in");
      const sel = cs ? `\${${ge(n.id, "selector_in")}}` : (n.f.selector || ".box");
      const props = cp ? `\${${ge(n.id, "props_in")}}` : (n.f.props || "");
      return `\`${sel} { ${props} }\``;
    },
  },
  css_property: {
    label: "css property",
    cat: "css",
    col: "var(--col-css)",
    fields: [
      { id: "prop", label: "property", kind: "text", def: "color" },
      { id: "val", label: "value", kind: "text", def: "red" },
    ],
    ins: [{ id: "val_in", label: "value (wired)" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === "val_in");
      const val = c ? `\${${ge(n.id, "val_in")}}` : (n.f.val || "red");
      return `\`${n.f.prop || "color"}: ${val};\``;
    },
  },
  css_concat: {
    label: "css concat",
    cat: "css",
    col: "var(--col-css)",
    fields: [],
    ins: [
      { id: "a", label: "rule a" },
      { id: "b", label: "rule b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} + " " + ${ge(n.id, "b")})`,
  },
  css_var: {
    label: "css variable",
    cat: "css",
    col: "var(--col-css)",
    fields: [
      { id: "name", label: "var name", kind: "text", def: "--color" },
      { id: "val", label: "value", kind: "text", def: "#ff0000" },
    ],
    ins: [{ id: "val_in", label: "value (wired)" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === "val_in");
      const val = c ? `\${${ge(n.id, "val_in")}}` : (n.f.val || "#ff0000");
      return `\`${n.f.name || "--color"}: ${val};\``;
    },
  },
  css_var_ref: {
    label: "var() ref",
    cat: "css",
    col: "var(--col-css)",
    fields: [
      { id: "name", label: "var name", kind: "text", def: "--color" },
      { id: "fallback", label: "fallback", kind: "text", def: "" },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => {
      const fb = n.f.fallback ? `, ${n.f.fallback}` : "";
      return `"var(${n.f.name || "--color"}${fb})"`;
    },
  },
  css_media: {
    label: "media query",
    cat: "css",
    col: "var(--col-css)",
    fields: [
      { id: "query", label: "query", kind: "text", def: "max-width: 768px" },
    ],
    ins: [{ id: "rules", label: "rules" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `\`@media (${n.f.query || "max-width: 768px"}) { \${${ge(n.id, "rules")}} }\``,
  },
  css_keyframes: {
    label: "keyframes",
    cat: "css",
    col: "var(--col-css)",
    fields: [
      { id: "name", label: "name", kind: "text", def: "fadeIn" },
      { id: "frames", label: "frames (raw css)", kind: "text", def: "from { opacity: 0; } to { opacity: 1; }" },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `"@keyframes ${n.f.name || "fadeIn"} { ${n.f.frames || ""} }"`,
  },
  css_class_builder: {
    label: "class builder",
    cat: "css",
    col: "var(--col-css)",
    fields: [{ id: "base", label: "base class", kind: "text", def: "box" }],
    ins: [
      { id: "a", label: "class a" },
      { id: "b", label: "class b" },
      { id: "c", label: "class c" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const parts = ["a", "b", "c"]
        .filter((v) => Object.values(conns).find((c) => c.tn === n.id && c.tp === v))
        .map((v) => `\${${ge(n.id, v)}}`);
      const base = n.f.base ? n.f.base + " " : "";
      return `\`${base}${parts.join(" ")}\``;
    },
  },
  css_inline: {
    label: "inline style",
    cat: "css",
    col: "var(--col-css)",
    fields: [{ id: "styles", label: "styles", kind: "text", def: "color: red; font-size: 16px;" }],
    ins: [{ id: "styles_in", label: "styles (wired)" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === "styles_in");
      const styles = c ? ge(n.id, "styles_in") : `"${n.f.styles || ""}"`;
      return `\`style="\${${styles}}"\``;
    },
  },
  css_vars_block: {
    label: ":root vars",
    cat: "css",
    col: "var(--col-css)",
    fields: [{ id: "vars", label: "vars (raw css)", kind: "text", def: "--color: red;\n--size: 16px;" }],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `":root { ${n.f.vars || ""} }"`,
  },
  css_reset: {
    label: "css reset",
    cat: "css",
    col: "var(--col-css)",
    fields: [],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: () => `"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }"`,
  },
  css_flexbox: {
    label: "flexbox",
    cat: "css",
    col: "var(--col-css)",
    fields: [
      { id: "selector", label: "selector", kind: "text", def: ".flex" },
      {
        id: "direction",
        label: "direction",
        kind: "select",
        opts: ["row", "column", "row-reverse", "column-reverse"],
        def: "row",
      },
      {
        id: "justify",
        label: "justify",
        kind: "select",
        opts: ["flex-start", "flex-end", "center", "space-between", "space-around", "space-evenly"],
        def: "flex-start",
      },
      {
        id: "align",
        label: "align",
        kind: "select",
        opts: ["stretch", "flex-start", "flex-end", "center", "baseline"],
        def: "stretch",
      },
      { id: "gap", label: "gap", kind: "text", def: "0" },
      {
        id: "wrap",
        label: "wrap",
        kind: "select",
        opts: ["nowrap", "wrap", "wrap-reverse"],
        def: "nowrap",
      },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `"${n.f.selector || ".flex"} { display: flex; flex-direction: ${n.f.direction || "row"}; justify-content: ${n.f.justify || "flex-start"}; align-items: ${n.f.align || "stretch"}; gap: ${n.f.gap || "0"}; flex-wrap: ${n.f.wrap || "nowrap"}; }"`,
  },
  css_grid: {
    label: "grid",
    cat: "css",
    col: "var(--col-css)",
    fields: [
      { id: "selector", label: "selector", kind: "text", def: ".grid" },
      { id: "columns", label: "columns", kind: "text", def: "repeat(3, 1fr)" },
      { id: "rows", label: "rows", kind: "text", def: "auto" },
      { id: "gap", label: "gap", kind: "text", def: "1rem" },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `"${n.f.selector || ".grid"} { display: grid; grid-template-columns: ${n.f.columns || "repeat(3, 1fr)"}; grid-template-rows: ${n.f.rows || "auto"}; gap: ${n.f.gap || "1rem"}; }"`,
  },
  css_animation: {
    label: "animation prop",
    cat: "css",
    col: "var(--col-css)",
    fields: [
      { id: "name", label: "name", kind: "text", def: "fadeIn" },
      { id: "duration", label: "duration", kind: "text", def: "0.3s" },
      { id: "easing", label: "easing", kind: "text", def: "ease" },
      { id: "delay", label: "delay", kind: "text", def: "0s" },
      { id: "iteration", label: "iterations", kind: "text", def: "1" },
      {
        id: "fill",
        label: "fill mode",
        kind: "select",
        opts: ["none", "forwards", "backwards", "both"],
        def: "none",
      },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `"animation: ${n.f.name || "fadeIn"} ${n.f.duration || "0.3s"} ${n.f.easing || "ease"} ${n.f.delay || "0s"} ${n.f.iteration || "1"} ${n.f.fill || "none"};"`,
  },
  css_transition: {
    label: "transition prop",
    cat: "css",
    col: "var(--col-css)",
    fields: [
      { id: "prop", label: "property", kind: "text", def: "all" },
      { id: "duration", label: "duration", kind: "text", def: "0.2s" },
      { id: "easing", label: "easing", kind: "text", def: "ease" },
      { id: "delay", label: "delay", kind: "text", def: "0s" },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `"transition: ${n.f.prop || "all"} ${n.f.duration || "0.2s"} ${n.f.easing || "ease"} ${n.f.delay || "0s"};"`,
  },
  css_color: {
    label: "color value",
    cat: "css",
    col: "var(--col-css)",
    fields: [
      {
        id: "format",
        label: "format",
        kind: "select",
        opts: ["hex", "rgb", "hsl", "oklch", "named"],
        def: "hex",
      },
      { id: "val", label: "value", kind: "text", def: "#ff0000" },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `"${n.f.val || "#ff0000"}"`,
  },
  css_set_var: {
    label: "set css var",
    cat: "css",
    col: "var(--col-css)",
    fields: [{ id: "name", label: "var name", kind: "text", def: "--color" }],
    ins: [
      { id: "el", label: "element" },
      { id: "val", label: "value" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "el")}.style.setProperty("${n.f.name || "--color"}", ${ge(n.id, "val")});`,
  },
  css_get_var: {
    label: "get css var",
    cat: "css",
    col: "var(--col-css)",
    fields: [{ id: "name", label: "var name", kind: "text", def: "--color" }],
    ins: [{ id: "el", label: "element" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `getComputedStyle(${ge(n.id, "el")}).getPropertyValue("${n.f.name || "--color"}")`,
  },
  regex_create: {
    label: "new RegExp",
    cat: "regex",
    col: "var(--col-regex)",
    fields: [
      { id: "pattern", label: "pattern", kind: "text", def: "\\w+" },
      { id: "flags", label: "flags", kind: "text", def: "g" },
    ],
    ins: [
      { id: "pattern_in", label: "pattern (wired)" },
      { id: "flags_in", label: "flags (wired)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const cp = Object.values(conns).find((c) => c.tn === n.id && c.tp === "pattern_in");
      const cf = Object.values(conns).find((c) => c.tn === n.id && c.tp === "flags_in");
      const pat = cp ? ge(n.id, "pattern_in") : `"${(n.f.pattern || "\\w+").replace(/\\/g, "\\\\")}"`;
      const flags = cf ? ge(n.id, "flags_in") : `"${n.f.flags || "g"}"`;
      return `new RegExp(${pat}, ${flags})`;
    },
  },
  regex_literal: {
    label: "regex literal",
    cat: "regex",
    col: "var(--col-regex)",
    fields: [
      { id: "pattern", label: "pattern", kind: "text", def: "\\w+" },
      { id: "flags", label: "flags", kind: "text", def: "g" },
    ],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `/${n.f.pattern || "\\w+"}/${n.f.flags || "g"}`,
  },
  regex_test: {
    label: "regex.test()",
    cat: "regex",
    col: "var(--col-regex)",
    fields: [],
    ins: [
      { id: "regex", label: "regex" },
      { id: "str", label: "string" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "regex")}.test(${ge(n.id, "str")})`,
  },
  regex_exec: {
    label: "regex.exec()",
    cat: "regex",
    col: "var(--col-regex)",
    fields: [],
    ins: [
      { id: "regex", label: "regex" },
      { id: "str", label: "string" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "regex")}.exec(${ge(n.id, "str")})`,
  },
  regex_match_all: {
    label: "matchAll",
    cat: "regex",
    col: "var(--col-regex)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "regex", label: "regex" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `[...${ge(n.id, "str")}.matchAll(${ge(n.id, "regex")})]`,
  },
  regex_replace: {
    label: "regex replace",
    cat: "regex",
    col: "var(--col-regex)",
    fields: [{ id: "replacement", label: "replacement", kind: "text", def: "" }],
    ins: [
      { id: "str", label: "string" },
      { id: "regex", label: "regex" },
      { id: "repl_in", label: "replacement (wired)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === "repl_in");
      const repl = c ? ge(n.id, "repl_in") : `"${n.f.replacement || ""}"`;
      return `${ge(n.id, "str")}.replace(${ge(n.id, "regex")}, ${repl})`;
    },
  },
  regex_split: {
    label: "regex split",
    cat: "regex",
    col: "var(--col-regex)",
    fields: [],
    ins: [
      { id: "str", label: "string" },
      { id: "regex", label: "regex" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "str")}.split(${ge(n.id, "regex")})`,
  },
  err_create: {
    label: "new Error",
    cat: "control",
    col: "var(--col-flow)",
    fields: [{ id: "msg", label: "message", kind: "text", def: "something went wrong" }],
    ins: [{ id: "msg_in", label: "message (wired)" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === "msg_in");
      const msg = c ? ge(n.id, "msg_in") : `"${n.f.msg || "something went wrong"}"`;
      return `new Error(${msg})`;
    },
  },
  err_type: {
    label: "typed Error",
    cat: "control",
    col: "var(--col-flow)",
    fields: [
      {
        id: "type",
        label: "type",
        kind: "select",
        opts: ["TypeError", "RangeError", "ReferenceError", "SyntaxError", "URIError", "EvalError"],
        def: "TypeError",
      },
      { id: "msg", label: "message", kind: "text", def: "invalid type" },
    ],
    ins: [{ id: "msg_in", label: "message (wired)" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === "msg_in");
      const msg = c ? ge(n.id, "msg_in") : `"${n.f.msg || "invalid type"}"`;
      return `new ${n.f.type || "TypeError"}(${msg})`;
    },
  },
  void_op: {
    label: "void",
    cat: "convert",
    col: "var(--col-conv)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `void ${ge(n.id, "val")}`,
  },
  comma_op: {
    label: "comma expr",
    cat: "control",
    col: "var(--col-flow)",
    fields: [],
    ins: [
      { id: "a", label: "a (run first)" },
      { id: "b", label: "b (return)" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")}, ${ge(n.id, "b")})`,
  },
  obj_create: {
    label: "Object.create",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "proto", label: "prototype" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Object.create(${ge(n.id, "proto")})`,
  },
  obj_define_prop: {
    label: "Object.defineProperty",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [
      { id: "key", label: "key", kind: "text", def: "prop" },
      { id: "descriptor", label: "descriptor (raw js)", kind: "text", def: "{ value: 42, writable: false }" },
    ],
    ins: [{ id: "obj", label: "object" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Object.defineProperty(${ge(n.id, "obj")}, "${n.f.key || "prop"}", ${n.f.descriptor || "{}"})`,
  },
  obj_get_proto: {
    label: "getPrototypeOf",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "obj", label: "object" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Object.getPrototypeOf(${ge(n.id, "obj")})`,
  },
  obj_is: {
    label: "Object.is",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Object.is(${ge(n.id, "a")}, ${ge(n.id, "b")})`,
  },
  map_get: {
    label: "Map.get",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [
      { id: "map", label: "map" },
      { id: "key", label: "key" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "map")}.get(${ge(n.id, "key")})`,
  },
  map_set: {
    label: "Map.set",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [
      { id: "map", label: "map" },
      { id: "key", label: "key" },
      { id: "val", label: "value" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "map")}.set(${ge(n.id, "key")}, ${ge(n.id, "val")})`,
  },
  map_has: {
    label: "Map.has",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [
      { id: "map", label: "map" },
      { id: "key", label: "key" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "map")}.has(${ge(n.id, "key")})`,
  },
  map_delete: {
    label: "Map.delete",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [
      { id: "map", label: "map" },
      { id: "key", label: "key" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "map")}.delete(${ge(n.id, "key")});`,
  },
  map_size: {
    label: "Map.size",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "map", label: "map" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "map")}.size`,
  },
  set_add: {
    label: "Set.add",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "set", label: "set" },
      { id: "val", label: "value" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "set")}.add(${ge(n.id, "val")})`,
  },
  set_has: {
    label: "Set.has",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "set", label: "set" },
      { id: "val", label: "value" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "set")}.has(${ge(n.id, "val")})`,
  },
  set_delete: {
    label: "Set.delete",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "set", label: "set" },
      { id: "val", label: "value" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "set")}.delete(${ge(n.id, "val")});`,
  },
  set_size: {
    label: "Set.size",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [{ id: "set", label: "set" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "set")}.size`,
  },
  set_to_arr: {
    label: "Set to array",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [{ id: "set", label: "set" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `[...${ge(n.id, "set")}]`,
  },
  arr_unique: {
    label: "unique (dedup)",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `[...new Set(${ge(n.id, "arr")})]`,
  },
  arr_flatten: {
    label: "flat",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "depth", label: "depth", kind: "number", def: "1" }],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.flat(${n.f.depth || "1"})`,
  },
  arr_zip: {
    label: "zip arrays",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "a", label: "arr a" },
      { id: "b", label: "arr b" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "a")}.map((v, i) => [v, ${ge(n.id, "b")}[i]])`,
  },
  arr_chunk: {
    label: "chunk",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "size", label: "chunk size", kind: "number", def: "2" }],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Array.from({ length: Math.ceil(${ge(n.id, "arr")}.length / ${n.f.size || 2}) }, (_, i) => ${ge(n.id, "arr")}.slice(i * ${n.f.size || 2}, i * ${n.f.size || 2} + ${n.f.size || 2}))`,
  },
  arr_range: {
    label: "range",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [],
    ins: [
      { id: "start", label: "start" },
      { id: "end", label: "end" },
      { id: "step", label: "step" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const cs = Object.values(conns).find((c) => c.tn === n.id && c.tp === "step");
      const step = cs ? ge(n.id, "step") : "1";
      return `Array.from({ length: Math.ceil((${ge(n.id, "end")} - ${ge(n.id, "start")}) / ${step}) }, (_, i) => ${ge(n.id, "start")} + i * ${step})`;
    },
  },
  arr_group_by: {
    label: "group by",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "fn", label: "key fn", kind: "text", def: "x => x.type" }],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.reduce((acc, x) => { const k = (${n.f.fn || "x => x"})(x); (acc[k] = acc[k] || []).push(x); return acc; }, {})`,
  },
  arr_count: {
    label: "count by",
    cat: "arrays",
    col: "var(--col-array)",
    fields: [{ id: "fn", label: "key fn", kind: "text", def: "x => x" }],
    ins: [{ id: "arr", label: "array" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "arr")}.reduce((acc, x) => { const k = (${n.f.fn || "x => x"})(x); acc[k] = (acc[k] || 0) + 1; return acc; }, {})`,
  },
  url_create: {
    label: "new URL",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "base", label: "base url", kind: "text", def: "" }],
    ins: [{ id: "url", label: "url string" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const base = n.f.base ? `, "${n.f.base}"` : "";
      return `new URL(${ge(n.id, "url")}${base})`;
    },
  },
  url_search_params: {
    label: "URLSearchParams",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "init", label: "init (raw js)", kind: "text", def: "" }],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `new URLSearchParams(${n.f.init ? `{${n.f.init}}` : ""})`,
  },
  abort_controller: {
    label: "AbortController",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "name", label: "var name", kind: "text", def: "controller" }],
    ins: [],
    outs: [{ id: "out", label: "controller" }],
    expr: false,
    stmt: true,
    gen: (n) => `const ${n.f.name || "controller"} = new AbortController();`,
    ref: (n) => n.f.name || "controller",
  },
  abort_signal: {
    label: "abort signal",
    cat: "async",
    col: "var(--col-async)",
    fields: [],
    ins: [{ id: "controller", label: "controller" }],
    outs: [{ id: "out", label: "signal" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "controller")}.signal`,
  },
  abort_abort: {
    label: "abort()",
    cat: "async",
    col: "var(--col-async)",
    fields: [],
    ins: [{ id: "controller", label: "controller" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "controller")}.abort();`,
  },
  queue_microtask: {
    label: "queueMicrotask",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "fn", label: "callback", kind: "text", def: "() => {}" }],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => `queueMicrotask(${n.f.fn || "() => {}"});`,
  },
  request_animation_frame: {
    label: "requestAnimationFrame",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "fn", label: "callback", kind: "text", def: "(t) => {}" }],
    ins: [],
    outs: [{ id: "out", label: "id" }],
    expr: true,
    gen: (n) => `requestAnimationFrame(${n.f.fn || "(t) => {}"})`,
  },
  cancel_animation_frame: {
    label: "cancelAnimationFrame",
    cat: "async",
    col: "var(--col-async)",
    fields: [],
    ins: [{ id: "id", label: "frame id" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `cancelAnimationFrame(${ge(n.id, "id")});`,
  },
  fetch_json: {
    label: "fetch JSON",
    cat: "async",
    col: "var(--col-async)",
    fields: [
      {
        id: "method",
        label: "method",
        kind: "select",
        opts: ["GET", "POST", "PUT", "DELETE", "PATCH"],
        def: "GET",
      },
    ],
    ins: [
      { id: "url", label: "url" },
      { id: "body", label: "body" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const hasBody = Object.values(conns).find((c) => c.tn === n.id && c.tp === "body");
      const opts = [`method: "${n.f.method || "GET"}"`, `headers: { "content-type": "application/json" }`];
      if (hasBody) opts.push(`body: JSON.stringify(${ge(n.id, "body")})`);
      return `fetch(${ge(n.id, "url")}, { ${opts.join(", ")} }).then(r => r.json())`;
    },
  },
  insert_before: {
    label: "insertBefore",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [],
    ins: [
      { id: "parent", label: "parent" },
      { id: "newEl", label: "new element" },
      { id: "ref", label: "reference element" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "parent")}.insertBefore(${ge(n.id, "newEl")}, ${ge(n.id, "ref")});`,
  },
  insert_adjacent: {
    label: "insertAdjacentHTML",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [
      {
        id: "position",
        label: "position",
        kind: "select",
        opts: ["beforebegin", "afterbegin", "beforeend", "afterend"],
        def: "beforeend",
      },
    ],
    ins: [
      { id: "el", label: "element" },
      { id: "html", label: "html string" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "el")}.insertAdjacentHTML("${n.f.position || "beforeend"}", ${ge(n.id, "html")});`,
  },
  clone_node: {
    label: "cloneNode",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [
      {
        id: "deep",
        label: "deep",
        kind: "select",
        opts: ["true", "false"],
        def: "true",
      },
    ],
    ins: [{ id: "el", label: "element" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "el")}.cloneNode(${n.f.deep || "true"})`,
  },
  replace_child: {
    label: "replaceChild",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [],
    ins: [
      { id: "parent", label: "parent" },
      { id: "newEl", label: "new element" },
      { id: "oldEl", label: "old element" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "parent")}.replaceChild(${ge(n.id, "newEl")}, ${ge(n.id, "oldEl")});`,
  },
  contains: {
    label: "contains",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [],
    ins: [
      { id: "parent", label: "parent" },
      { id: "child", label: "child" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "parent")}.contains(${ge(n.id, "child")})`,
  },
  closest: {
    label: "closest",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "sel", label: "selector", kind: "text", def: ".parent" }],
    ins: [{ id: "el", label: "element" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "el")}.closest("${n.f.sel || ".parent"}")`,
  },
  matches: {
    label: "matches",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "sel", label: "selector", kind: "text", def: ".active" }],
    ins: [{ id: "el", label: "element" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "el")}.matches("${n.f.sel || ".active"}")`,
  },
  get_bounding_rect: {
    label: "getBoundingClientRect",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [],
    ins: [{ id: "el", label: "element" }],
    outs: [{ id: "out", label: "rect" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "el")}.getBoundingClientRect()`,
  },
  scroll_into_view: {
    label: "scrollIntoView",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [
      {
        id: "behavior",
        label: "behavior",
        kind: "select",
        opts: ["smooth", "instant", "auto"],
        def: "smooth",
      },
      {
        id: "block",
        label: "block",
        kind: "select",
        opts: ["start", "center", "end", "nearest"],
        def: "start",
      },
    ],
    ins: [{ id: "el", label: "element" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "el")}.scrollIntoView({ behavior: "${n.f.behavior || "smooth"}", block: "${n.f.block || "start"}" });`,
  },
  dispatch_event: {
    label: "dispatchEvent",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [
      { id: "event", label: "event name", kind: "text", def: "click" },
      {
        id: "bubbles",
        label: "bubbles",
        kind: "select",
        opts: ["true", "false"],
        def: "true",
      },
    ],
    ins: [{ id: "el", label: "element" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "el")}.dispatchEvent(new CustomEvent("${n.f.event || "click"}", { bubbles: ${n.f.bubbles || "true"} }));`,
  },
  create_text_node: {
    label: "createTextNode",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [],
    ins: [{ id: "text", label: "text" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `document.createTextNode(${ge(n.id, "text")})`,
  },
  doc_fragment: {
    label: "DocumentFragment",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: () => `document.createDocumentFragment()`,
  },
  dataset_get: {
    label: "dataset.get",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "key", label: "key", kind: "text", def: "id" }],
    ins: [{ id: "el", label: "element" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "el")}.dataset.${n.f.key || "id"}`,
  },
  dataset_set: {
    label: "dataset.set",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "key", label: "key", kind: "text", def: "id" }],
    ins: [
      { id: "el", label: "element" },
      { id: "val", label: "value" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "el")}.dataset.${n.f.key || "id"} = ${ge(n.id, "val")};`,
  },
  remove_event: {
    label: "removeEventListener",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "event", label: "event", kind: "text", def: "click" }],
    ins: [
      { id: "el", label: "element" },
      { id: "fn", label: "handler ref" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${ge(n.id, "el")}.removeEventListener("${n.f.event || "click"}", ${ge(n.id, "fn")});`,
  },
  get_computed_style: {
    label: "getComputedStyle",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [{ id: "prop", label: "property", kind: "text", def: "color" }],
    ins: [{ id: "el", label: "element" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `getComputedStyle(${ge(n.id, "el")}).${n.f.prop || "color"}`,
  },
  window_scroll: {
    label: "window.scrollTo",
    cat: "dom",
    col: "var(--col-dom)",
    fields: [
      {
        id: "behavior",
        label: "behavior",
        kind: "select",
        opts: ["smooth", "instant"],
        def: "smooth",
      },
    ],
    ins: [
      { id: "x", label: "x" },
      { id: "y", label: "y" },
    ],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `window.scrollTo({ left: ${ge(n.id, "x")}, top: ${ge(n.id, "y")}, behavior: "${n.f.behavior || "smooth"}" });`,
  },
  local_storage_remove: {
    label: "localStorage.remove",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "key", label: "key", kind: "text", def: "myKey" }],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => `localStorage.removeItem("${n.f.key || "myKey"}");`,
  },
  session_storage_get: {
    label: "sessionStorage.get",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "key", label: "key", kind: "text", def: "myKey" }],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n) => `sessionStorage.getItem("${n.f.key || "myKey"}")`,
  },
  session_storage_set: {
    label: "sessionStorage.set",
    cat: "async",
    col: "var(--col-async)",
    fields: [{ id: "key", label: "key", kind: "text", def: "myKey" }],
    ins: [{ id: "val", label: "value" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `sessionStorage.setItem("${n.f.key || "myKey"}", ${ge(n.id, "val")});`,
  },
  console_group: {
    label: "console.group",
    cat: "output",
    col: "var(--col-out)",
    fields: [{ id: "label", label: "label", kind: "text", def: "group" }],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => `console.group("${n.f.label || "group"}");`,
  },
  console_group_end: {
    label: "console.groupEnd",
    cat: "output",
    col: "var(--col-out)",
    fields: [],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: () => `console.groupEnd();`,
  },
  console_time: {
    label: "console.time",
    cat: "output",
    col: "var(--col-out)",
    fields: [{ id: "label", label: "label", kind: "text", def: "timer" }],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => `console.time("${n.f.label || "timer"}");`,
  },
  console_time_end: {
    label: "console.timeEnd",
    cat: "output",
    col: "var(--col-out)",
    fields: [{ id: "label", label: "label", kind: "text", def: "timer" }],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => `console.timeEnd("${n.f.label || "timer"}");`,
  },
  console_count: {
    label: "console.count",
    cat: "output",
    col: "var(--col-out)",
    fields: [{ id: "label", label: "label", kind: "text", def: "count" }],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => `console.count("${n.f.label || "count"}");`,
  },
  console_dir: {
    label: "console.dir",
    cat: "output",
    col: "var(--col-out)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `console.dir(${ge(n.id, "val")});`,
  },
  console_assert: {
    label: "console.assert",
    cat: "output",
    col: "var(--col-out)",
    fields: [{ id: "msg", label: "message", kind: "text", def: "assertion failed" }],
    ins: [{ id: "cond", label: "condition" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `console.assert(${ge(n.id, "cond")}, "${n.f.msg || "assertion failed"}");`,
  },
  math_lerp: {
    label: "lerp",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "a", label: "a" },
      { id: "b", label: "b" },
      { id: "t", label: "t" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} + (${ge(n.id, "b")} - ${ge(n.id, "a")}) * ${ge(n.id, "t")})`,
  },
  math_map: {
    label: "map range",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "val", label: "value" },
      { id: "in_min", label: "in min" },
      { id: "in_max", label: "in max" },
      { id: "out_min", label: "out min" },
      { id: "out_max", label: "out max" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `((${ge(n.id, "val")} - ${ge(n.id, "in_min")}) / (${ge(n.id, "in_max")} - ${ge(n.id, "in_min")}) * (${ge(n.id, "out_max")} - ${ge(n.id, "out_min")}) + ${ge(n.id, "out_min")})`,
  },
  math_deg_to_rad: {
    label: "deg → rad",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "deg", label: "degrees" }],
    outs: [{ id: "out", label: "radians" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "deg")} * Math.PI / 180)`,
  },
  math_rad_to_deg: {
    label: "rad → deg",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [{ id: "rad", label: "radians" }],
    outs: [{ id: "out", label: "degrees" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "rad")} * 180 / Math.PI)`,
  },
  math_atan2: {
    label: "atan2",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "y", label: "y" },
      { id: "x", label: "x" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.atan2(${ge(n.id, "y")}, ${ge(n.id, "x")})`,
  },
  math_distance: {
    label: "distance 2D",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "x1", label: "x1" },
      { id: "y1", label: "y1" },
      { id: "x2", label: "x2" },
      { id: "y2", label: "y2" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.hypot(${ge(n.id, "x2")} - ${ge(n.id, "x1")}, ${ge(n.id, "y2")} - ${ge(n.id, "y1")})`,
  },
  math_random_range: {
    label: "random range",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "min", label: "min" },
      { id: "max", label: "max" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `(Math.random() * (${ge(n.id, "max")} - ${ge(n.id, "min")}) + ${ge(n.id, "min")})`,
  },
  math_random_int: {
    label: "random int",
    cat: "math",
    col: "var(--col-math)",
    fields: [],
    ins: [
      { id: "min", label: "min" },
      { id: "max", label: "max" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `Math.floor(Math.random() * (${ge(n.id, "max")} - ${ge(n.id, "min")} + 1) + ${ge(n.id, "min")})`,
  },
  incr: {
    label: "increment",
    cat: "variables",
    col: "var(--col-var)",
    fields: [{ id: "name", label: "variable", kind: "text", def: "i" }],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => `${n.f.name || "i"}++;`,
  },
  decr: {
    label: "decrement",
    cat: "variables",
    col: "var(--col-var)",
    fields: [{ id: "name", label: "variable", kind: "text", def: "i" }],
    ins: [],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n) => `${n.f.name || "i"}--;`,
  },
  assign_op: {
    label: "assign op",
    cat: "variables",
    col: "var(--col-var)",
    fields: [
      { id: "name", label: "variable", kind: "text", def: "x" },
      {
        id: "op",
        label: "operator",
        kind: "select",
        opts: ["+=", "-=", "*=", "/=", "%=", "**=", "&&=", "||=", "??=", "&=", "|=", "^=", "<<=", ">>="],
        def: "+=",
      },
    ],
    ins: [{ id: "val", label: "value" }],
    outs: [],
    expr: false,
    stmt: true,
    gen: (n, ge) => `${n.f.name || "x"} ${n.f.op || "+="} ${ge(n.id, "val")};`,
  },
  date_get_year: {
    label: "getFullYear",
    cat: "date",
    col: "var(--col-date)",
    fields: [],
    ins: [{ id: "date", label: "date" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "date")}.getFullYear()`,
  },
  date_get_month: {
    label: "getMonth",
    cat: "date",
    col: "var(--col-date)",
    fields: [],
    ins: [{ id: "date", label: "date" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "date")}.getMonth()`,
  },
  date_get_day: {
    label: "getDate",
    cat: "date",
    col: "var(--col-date)",
    fields: [],
    ins: [{ id: "date", label: "date" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "date")}.getDate()`,
  },
  date_get_hours: {
    label: "getHours",
    cat: "date",
    col: "var(--col-date)",
    fields: [],
    ins: [{ id: "date", label: "date" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "date")}.getHours()`,
  },
  date_get_minutes: {
    label: "getMinutes",
    cat: "date",
    col: "var(--col-date)",
    fields: [],
    ins: [{ id: "date", label: "date" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "date")}.getMinutes()`,
  },
  date_get_seconds: {
    label: "getSeconds",
    cat: "date",
    col: "var(--col-date)",
    fields: [],
    ins: [{ id: "date", label: "date" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "date")}.getSeconds()`,
  },
  date_to_iso: {
    label: "toISOString",
    cat: "date",
    col: "var(--col-date)",
    fields: [],
    ins: [{ id: "date", label: "date" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "date")}.toISOString()`,
  },
  date_to_time: {
    label: "toLocaleTimeString",
    cat: "date",
    col: "var(--col-date)",
    fields: [{ id: "locale", label: "locale", kind: "text", def: "en-US" }],
    ins: [{ id: "date", label: "date" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "date")}.toLocaleTimeString("${n.f.locale || "en-US"}")`,
  },
  date_diff: {
    label: "date diff (ms)",
    cat: "date",
    col: "var(--col-date)",
    fields: [],
    ins: [
      { id: "a", label: "date a" },
      { id: "b", label: "date b" },
    ],
    outs: [{ id: "out", label: "ms" }],
    expr: true,
    gen: (n, ge) => `(${ge(n.id, "a")} - ${ge(n.id, "b")})`,
  },
  class_def: {
    label: "class",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [
      { id: "name", label: "name", kind: "text", def: "MyClass" },
      { id: "extends_cls", label: "extends", kind: "text", def: "" },
      { id: "body", label: "body (raw js)", kind: "text", def: "constructor() {}" },
    ],
    ins: [],
    outs: [{ id: "ref", label: "ref" }],
    expr: false,
    stmt: true,
    gen: (n) => {
      const ext = n.f.extends_cls ? ` extends ${n.f.extends_cls}` : "";
      return `class ${n.f.name || "MyClass"}${ext} {\n  ${n.f.body || "constructor() {}"}\n}`;
    },
    ref: (n) => n.f.name || "MyClass",
  },
  new_instance: {
    label: "new instance",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [{ id: "cls", label: "class name", kind: "text", def: "MyClass" }],
    ins: [
      { id: "a0", label: "arg 1" },
      { id: "a1", label: "arg 2" },
      { id: "a2", label: "arg 3" },
    ],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => {
      const args = ["a0", "a1", "a2"]
        .map((a) => {
          const c = Object.values(conns).find((c) => c.tn === n.id && c.tp === a);
          return c ? ge(n.id, a) : null;
        })
        .filter(Boolean);
      return `new ${n.f.cls || "MyClass"}(${args.join(", ")})`;
    },
  },
  generator_fn: {
    label: "generator fn",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [
      { id: "name", label: "name", kind: "text", def: "gen" },
      { id: "params", label: "params", kind: "text", def: "" },
      { id: "body", label: "body (raw js)", kind: "text", def: "yield 1; yield 2;" },
    ],
    ins: [],
    outs: [{ id: "ref", label: "ref" }],
    expr: false,
    stmt: true,
    gen: (n) => `function* ${n.f.name || "gen"}(${n.f.params || ""}) {\n  ${n.f.body || ""}\n}`,
    ref: (n) => n.f.name || "gen",
  },
  yield_node: {
    label: "yield",
    cat: "functions",
    col: "var(--col-fn)",
    fields: [],
    ins: [{ id: "val", label: "value" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `yield ${ge(n.id, "val")}`,
  },
  proxy_node: {
    label: "Proxy",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [{ id: "handler", label: "handler (raw js)", kind: "text", def: "{ get(t,k) { return t[k]; } }" }],
    ins: [{ id: "target", label: "target" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `new Proxy(${ge(n.id, "target")}, ${n.f.handler || "{}"})`,
  },
  weakmap_node: {
    label: "new WeakMap",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: () => `new WeakMap()`,
  },
  weakref_node: {
    label: "new WeakRef",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "target", label: "target" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `new WeakRef(${ge(n.id, "target")})`,
  },
  weakref_deref: {
    label: "WeakRef.deref()",
    cat: "objects",
    col: "var(--col-obj)",
    fields: [],
    ins: [{ id: "ref", label: "weakref" }],
    outs: [{ id: "out", label: "out" }],
    expr: true,
    gen: (n, ge) => `${ge(n.id, "ref")}.deref()`,
  },
};

Object.assign(TYPES, TYPES_ADDITIONS);
